on:
   push:
    branches:
      - main
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install dependencies  
        run: yarn install

      - name: run test
        run: yarn test

      - name: build
        run: yarn build
